### ISSUE TITLE
How well does this work in practice?

### ISSUE THREAD

**Issue by ahundt** [titu1994/Snapshot-Ensembles#6]
Have you used this at all in your own work and found it effective?

I've got to several long training runs and it could be helpful to get the improvements the authors describe, plus the decent intermediate results while I wait.

**Comment by titu1994** [comment]
Truthfully, I don't really use it in my projects. This is primarily because I dont like the inference time. The models I work with, and more generally, huge models, have a significant inference time. To ensemble them is to linearly increase inference time. While the performance benefits are good, it is simply too much to use it in any setting other than when one has all the time in the world to wait for results.

However, the ensembles can be also used in another way, which is to select the single best model from random initialization / local minimas. In such a scenario, yes, it is much more effective to find weights for a model which can get high performance without ensembles. However, I feel as I would rather just train a single model longer than hope for the best to get a strong model in a bunch of models.

**Comment by ahundt** [comment]
Cool, thanks! That's exactly the advice I was looking for.
